/**:
  ros__parameters:
    mock_mode: true
    port: "/dev/ttyUSB0"
    baudrate: 1000000
    joints:
      lower_yaw:
        id: 1
        model: "XM430-W210-T"
        min_angle_deg: -90.0
        max_angle_deg: 90.0
      lower_pitch:
        id: 2
        model: "XM430-W210-T"
        min_angle_deg: -45.0
        max_angle_deg: 45.0
      upper_yaw:
        id: 3
        model: "XL320"
        min_angle_deg: -90.0
        max_angle_deg: 90.0
      upper_pitch:
        id: 4
        model: "XL320"
        min_angle_deg: -45.0
        max_angle_deg: 45.0
